spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

